name: CI
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - name: Install Auto
        run: |
          curl -vkL -o - https://github.com/intuit/auto/releases/download/v11.3.0/auto-linux.gz | gunzip > ~/auto
          chmod a+x ~/auto

      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Build
        run: ./gradlew build

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_KEY: ${{ secrets.SIGNING_KEY }}
          DEPLOY_MAVEN_GPG_PASSPHRASE: ${{ secrets.SIGNING_PASS }}
          DEPLOY_MAVEN_USERNAME: ${{ secrets.SONA_USER }}
          DEPLOY_MAVEN_PASSWORD: ${{ secrets.SONA_PASS }}
        run:
          echo -e $GPG_KEY | gpg --import --batch
          echo -e "pinentry-mode loopback\npassphrase $DEPLOY_MAVEN_GPG_PASSPHRASE" > ~/.gnupg/gpg.conf
          ~/auto shipit -vvv
