name: CI
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - name: Install Auto
        run: |
          curl -vkL -o - https://github.com/intuit/auto/releases/download/v11.3.0/auto-linux.gz | gunzip > ~/auto
          chmod a+x ~/auto

      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Import GPG
        uses: crazy-max/ghaction-import-gpg@v6.3.0
        with:
          gpg_private_key: ${{ secrets.SIGNING_KEY }}
          passphrase: ${{ secrets.SIGNING_PASS }}

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          DEPLOY_MAVEN_USERNAME: ${{ secrets.SONA_USER }}
          DEPLOY_MAVEN_PASSWORD: ${{ secrets.SONA_PASS }}
          MAVEN_USER: ${{ secrets.SONA_USER }}
          MAVEN_PASSWORD: ${{ secrets.SONA_PASS }}
          GPG_SIGN: true
        run: ~/auto shipit -vvv
